from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text # Importar 'text' para comandos SQL brutos

# revision identifiers, used by Alembic.
revision: str = '214d67065a11'
down_revision: Union[str, Sequence[str], None] = '7cec6f592a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- CORREÇÃO DE INTEGRIDADE: Adição de score_credito ---
    
    # 1. Adiciona a coluna permitindo NULL (evita o NotNullViolation inicial)
    op.add_column('users', sa.Column('score_credito', sa.Integer(), nullable=True))
    
    # 2. Atualiza todas as linhas existentes, definindo um score padrão de 0
    # O valor 0 é usado pois ele é o valor padrão definido no seu models.py
    op.execute(
        text("UPDATE users SET score_credito = 0 WHERE score_credito IS NULL")
    )
    
    # 3. Altera a coluna para NOT NULL, garantindo a integridade daqui para frente
    op.alter_column('users', 'score_credito',
               existing_type=sa.Integer(),
               nullable=False)
               
    # --- FIM DA CORREÇÃO score_credito ---

    # Nota: Se o 'autogenerate' também incluiu op.create_table('transactions', ...) 
    # e op.create_table('credit_searches', ...) neste arquivo, elas devem vir aqui.
    # Como não foram fornecidas no traceback, assumimos que as correções acima são o foco principal.
    
    # Exemplo de outras criações que podem estar pendentes:
    # op.create_table('transactions', ...) 
    # op.create_table('credit_searches', ...)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # A reversão é simples, apenas remove a coluna
    op.drop_column('users', 'score_credito')
    # op.drop_table('credit_searches')
    # op.drop_table('transactions')
    # ### end Alembic commands ###