"""Create missing ledger and search tables

Revision ID: 9364ba73fd23
Revises: 3239be2dee11
Create Date: 2025-10-05 01:05:32.735119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9364ba73fd23'
down_revision: Union[str, Sequence[str], None] = '3239be2dee11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('desired_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('max_interest_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('desired_term_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NEGOTIATING', 'CANCELED', name='creditsearchstatus'), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_searches_id'), 'credit_searches', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('P2P_DEBITO', 'P2P_CREDITO', 'EMPRESTIMO_CONCEDIDO', 'PAGAMENTO_PARCELA', 'DEPOSITO', 'SAQUE', name='transactiontype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('origin_account_id', sa.Integer(), nullable=True),
    sa.Column('destination_account_id', sa.Integer(), nullable=True),
    sa.Column('reference_entity_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['destination_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['origin_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_reference_entity_id'), 'transactions', ['reference_entity_id'], unique=False)
    op.add_column('credit_offers', sa.Column('eligible_sector', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_offers', 'eligible_sector')
    op.drop_index(op.f('ix_transactions_reference_entity_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_credit_searches_id'), table_name='credit_searches')
    op.drop_table('credit_searches')
    # ### end Alembic commands ###
